# Generated by Django 4.2 on 2023-06-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_product_options_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
